name: ci

on:
  push:
    branches: [ main ]
    paths:
      - 'TermGlass/**'
      - '.github/workflows/ci.yml'
      - 'global.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'TermGlass/**'
      - '.github/workflows/ci.yml'
      - 'global.json'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
          cache: true

      - name: Restore
        run: dotnet restore TermGlass/TermGlass.csproj

      - name: Build (Release)
        run: dotnet build TermGlass/TermGlass.csproj -c Release --no-restore
